//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uav.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please input the brand. ")]
        public string brand { get; set; }
        [Required(ErrorMessage = "Please input the price. ")]
        public decimal price { get; set; }
        [Required(ErrorMessage = "Please input the buy date. ")]
        //[DataType(DataType.Date)]
        public System.DateTime buy_date { get; set; }
        [Required(ErrorMessage = "Please input the user name. ")]
        public int uid { get; set; }
    
        public virtual User User { get; set; }
    }
}
