//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uav.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please input your name. ")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please input your password. ")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please input your gender. ")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please input your country. ")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Please input your address. ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please input your email. ")]
        [EmailAddress(ErrorMessage="Please input a valid email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please input your phone number. ")]
        [Range(1, 99999999999)]
        public string Phone_number { get; set; }

    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
